### PR TITLE
practice wireframe

### PR DESCRIPTION
**Pull request by MishaHerscu**

### CODE REVIEW

**Comment by MishaHerscu** [comment]
I just downloaded Balsamiq and started messing around. How does this look?

**Comment by MishaHerscu** [comment]
What happens in terms of commits and version control when I am committing a file that isn't necessarily just lines of code? Is it just overwriting the old version of the file every time?

**Comment by jrhorn424** [comment]
> Is it just overwriting the old version of the file every time?

Maybe. I dunno. I just know you can't see a diff.

**Comment by jrhorn424** [comment]
I can't view this and give feedback, since I don't have Balsamiq and I don't want to. Maybe export as a PDF or PNG?

**Pull request closed without merging**
